GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzYwMDM3MjgwLCJleHAiOjE3NjAwMzcyOTV9.GUzEiSkbVTV1e_WCnyeRWHYuicDvHQFEJSULBg-Vo8k

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###
#return token and refresh token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Jimaaa",
  "password": "password123"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "Jimaaa",
  "password": "password123"
}
