

DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjMWY4ZDAwLTkzZGEtNDgxYi1iZWY5LTI3MjcyNTFjNDNiMyIsImVtYWlsIjoiZHNhZGFzQGRzYWRhLmNvbSIsImlhdCI6MTc2MDcwNDExMn0.SU4xPObeIkLnx44VQBX5GEyW9Ac7yOP54M1CmUX8JS0"
}

###

### Valid token validation
POST http://localhost:3001/validate-token
Content-Type: application/json
x-internal-api-key: 1234

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjMWY4ZDAwLTkzZGEtNDgxYi1iZWY5LTI3MjcyNTFjNDNiMyIsImVtYWlsIjoiZHNhZGFzQGRzYWRhLmNvbSIsImlhdCI6MTc2MDcwNDMxNywiZXhwIjoxNzYwNzA1MjE3fQ.STK4bnQ1p9f7qc8KFbPCfrBDlVElnuZ02NqgWjvDSOU"
}

### Missing token validation (should return 400 Bad Request)
POST http://localhost:3001/validate-token
Content-Type: application/json
x-internal-api-key: 1234

{}

###

#return token and refresh token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Jima",
  "password": "password123"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "Jima",
  "email": "dsadas@example.com",
  "password": "password123"
}

###

POST http://localhost:3000/auth/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU3NDYwN2RkLWZlOTEtNDAyMC04NDhiLTA3MmIzODY0YjI0OCIsImVtYWlsIjoiZHNhZGFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwOTQ4OTA3LCJleHAiOjE3NjA5NDk4MDd9.jmtIxglQZV_i_DPB4qK3Hg1MLsnJ1Sbdo5c2qWZ5bUg

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU3NDYwN2RkLWZlOTEtNDAyMC04NDhiLTA3MmIzODY0YjI0OCIsImVtYWlsIjoiZHNhZGFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwOTQ4OTA3fQ.qywJtRb5aelwRAFHkcON-I_ndIve-X9Zqtr9leMPG4w"
}

###

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEzZjRlNGU3LTYxMmItNGEzYy05NDcxLThjYjI0ZTU3YzJlMiIsImVtYWlsIjoiZHNhZGFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwOTQ3ODA4fQ.6DAjQr0GnkOpwopRdwFKcq4f0c2bC3BCbR5fW3He8o8