

DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwODkxODFkLTc4M2UtNDhhMi04MjIzLTQyMjU3Zjc4YjcwYSIsImVtYWlsIjoiZHNhZGFAeG1wbGUuY29tIiwiaWF0IjoxNzYwOTc3Njg1LCJleHAiOjE3NjE1ODI0ODV9.U_YzL2wt8gxd_LZG-nFdAP00WNwWWkdJCyzU7PWzbJs"
}

###

### Valid token validation
POST http://localhost:3000/auth/validate-token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiNWU3YTVkLTQ5ZjgtNDMwYi05N2JlLWNjNWZlNGU0M2NmMSIsImVtYWlsIjoiZHNhZGFAeG1wbGUuY29tIiwiaWF0IjoxNzYwOTc2MzU5fQ.7QX-FLZZwyU74C5LwIwQ0cz7IaBClLAuT2qEhwESYlM"
}

### Missing token validation (should return 400 Bad Request)
POST http://localhost:3001/validate-token
Content-Type: application/json
x-internal-api-key: 1234

{}

###

#return token and refresh token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ceccarellim7@gmail.com",
  "password": "Mrco@123_"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "MARCO",
  "email": "ceccarellim7@gmail.com",
  "password": "Mrco@123_"
}

###

POST http://localhost:3000/auth/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhMWJlMWE2LTc0MGEtNGNmYi05ZDQyLTNiMjQ4OTUzYTM1NSIsImVtYWlsIjoiZHNhZGFAeG1wbGUuY29tIiwiaWF0IjoxNzYwOTc3OTMxLCJleHAiOjE3NjE1ODI3MzF9.ItGl4zSBQhqOhOKFHHPSSqWyr1zYCnJqee6Cg6Z-SNw"
}

###

POST http://localhost:3000/auth/2fa
Content-Type: application/json

{
  "userId": "8612a985-0df8-49e3-8c41-525aff0b9b81",
  "otpCode": "112493"
}

###

PUT http://localhost:3001/update-user
Content-Type: application/json
x-internal-api-key: 1234

{
  "userId": "8612a985-0df8-49e3-8c41-525aff0b9b81",
  "username": "NewUsername",
  "tfaEnabled": false
}

###

PUT http://localhost:3000/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4MDViOThjLWMzOTItNGQ4MS04ODQxLTE0ZmM4ODM4Zjk2MiIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MTE0MDE4NSwiZXhwIjoxNzYxMTQwMjQ1fQ.jLVLdxLldtDmWg6xn8aKuUBXMidRiIeH8Wp2m8XfOIo

{
  "oldPassword": "Mrco@123_",
  "newPassword": "NewPassword456!"
}
