

DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljNTIzNjAxLTQzZDQtNDY3My1iNDczLWQ4MTM2ZGJhZTRiZCIsImVtYWlsIjoiZHNhZGFAeG1wbGUuY29tIiwiaWF0IjoxNzYwOTcyNjkwfQ.Znvxcoqun7Oz4trxLaVhdkpJNjNc-lSaRNrQajXHGSs"
}

###

### Valid token validation
POST http://localhost:3001/validate-token
Content-Type: application/json
x-internal-api-key: 1234

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlY2JhMTQwLTI2ODItNDZmZi05NzdkLWRiNzFlYjhkMWZhNiIsImVtYWlsIjoiZHNhZGFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwOTUwMzAyfQ.GNar6nHqSWjtsV5DTvThU5mdJtmCGisLh9-DvY5y9fI"
}

### Missing token validation (should return 400 Bad Request)
POST http://localhost:3001/validate-token
Content-Type: application/json
x-internal-api-key: 1234

{}

###

#return token and refresh token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "MARCo",
  "password": "Mrco@123_"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "MARCO",
  "email": "dsada@xmple.com",
  "password": "Mrco@123_"
}

###

POST http://localhost:3000/auth/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3ZTM4MGE3LTFiOTItNDY4Yi1hMmM3LWRmMGU3ZmRlYTAxZiIsImVtYWlsIjoiZHNhZGFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwOTY1MjM5fQ.OendX7cpTzn2e62L7hc4hY_u_vND4AEVAv7i-SCW61Y"
}

###

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEzZjRlNGU3LTYxMmItNGEzYy05NDcxLThjYjI0ZTU3YzJlMiIsImVtYWlsIjoiZHNhZGFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwOTQ3ODA4fQ.6DAjQr0GnkOpwopRdwFKcq4f0c2bC3BCbR5fW3He8o8