GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhMWJlMWE2LTc0MGEtNGNmYi05ZDQyLTNiMjQ4OTUzYTM1NSIsImVtYWlsIjoiZHNhZGFAeG1wbGUuY29tIiwiaWF0IjoxNzYwOTc3OTM5LCJleHAiOjE3NjA5Nzc5OTl9.oDnCcxSMGfmtFH9gR4ce-QcDXrkciUn9lqKoMicEaws

###

GET http://localhost:3002/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0Y2IyODIwLWE1YmYtNGQzZC1iOGU4LTdkNDEwOTc1ZWM1MSIsImVtYWlsIjoiZHNhZGFzQGRzYWRhLmNvbSIsImlhdCI6MTc2MDY5OTAzOCwiZXhwIjoxNzYwNjk5OTM4fQ.ViAEiIerdiVPelWU6MsFx71rY4nbJX6m_GjCyXp1bLI
