GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMjE3ZjE0LWUxMzItNGUxZi05OGZjLWRhZDJkOGUwNzc2MSIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MTEzOTg0NywiZXhwIjoxNzYxMTM5OTA3fQ.Vzmnf_X7-CxksbXS7DB3UvHbssN6jQTSbIXkDTynBhM
###

GET http://localhost:3002/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0Y2IyODIwLWE1YmYtNGQzZC1iOGU4LTdkNDEwOTc1ZWM1MSIsImVtYWlsIjoiZHNhZGFzQGRzYWRhLmNvbSIsImlhdCI6MTc2MDY5OTAzOCwiZXhwIjoxNzYwNjk5OTM4fQ.ViAEiIerdiVPelWU6MsFx71rY4nbJX6m_GjCyXp1bLI
