GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3OGVkYjhiLTEwYTUtNDNmZC04ZDllLTA0YjYxOTFhN2VjMiIsImVtYWlsIjoiZHNhZGFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwOTU3OTkwLCJleHAiOjE3NjA5NTg4OTB9.EoBCelafSOSvewzDwrkwL1DHcEE0i6KU9wmjDwZJXBE

###

GET http://localhost:3002/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0Y2IyODIwLWE1YmYtNGQzZC1iOGU4LTdkNDEwOTc1ZWM1MSIsImVtYWlsIjoiZHNhZGFzQGRzYWRhLmNvbSIsImlhdCI6MTc2MDY5OTAzOCwiZXhwIjoxNzYwNjk5OTM4fQ.ViAEiIerdiVPelWU6MsFx71rY4nbJX6m_GjCyXp1bLI
