

DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwODkxODFkLTc4M2UtNDhhMi04MjIzLTQyMjU3Zjc4YjcwYSIsImVtYWlsIjoiZHNhZGFAeG1wbGUuY29tIiwiaWF0IjoxNzYwOTc3Njg1LCJleHAiOjE3NjE1ODI0ODV9.U_YzL2wt8gxd_LZG-nFdAP00WNwWWkdJCyzU7PWzbJs"
}

###

### Valid token validation
POST http://localhost:3000/auth/validate-token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiNWU3YTVkLTQ5ZjgtNDMwYi05N2JlLWNjNWZlNGU0M2NmMSIsImVtYWlsIjoiZHNhZGFAeG1wbGUuY29tIiwiaWF0IjoxNzYwOTc2MzU5fQ.7QX-FLZZwyU74C5LwIwQ0cz7IaBClLAuT2qEhwESYlM"
}

### Missing token validation (should return 400 Bad Request)
POST http://localhost:3001/validate-token
Content-Type: application/json
x-internal-api-key: 1234

{}

###

#return token and refresh token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ceccarellim7@gmail.com",
  "password": "Mrco@123_"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "MARCO",
  "email": "ceccarellim7@gmail.com",
  "password": "Mrco@123_"
}

###

POST http://localhost:3000/auth/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViY2M3MjhhLTM4NzktNGU4OS1iNDJkLWY5NjBjOTQ0OGNmZSIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MTI5NDI0MCwiZXhwIjoxNzYxODk5MDQwfQ.PvSfcWkINty1ozzylOsSK57B4FFPbQVjuSmM0rD6DDI"
}

###

POST http://localhost:3000/auth/2fa
Content-Type: application/json

{
  "userId": "b6adbbf3-29e8-45ad-94ee-07330db6a732",
  "otpCode": "384493"
}

###

PUT http://localhost:3000/auth/enable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2YWRiYmYzLTI5ZTgtNDVhZC05NGVlLTA3MzMwZGI2YTczMiIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MTI5NTIxMSwiZXhwIjoxNzYxMjk1MjcxfQ.zx5pOEHkx1FyLs5cDICRUgdzXqhUn9VkaMXoFZm0ZsY

{
  "userId": "cf3696cf-7bac-4d96-be58-94e22c42880f",
  "tfaEnabled": false
}

###

PUT http://localhost:3000/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlZDQyODM4LTU5ZTEtNDFkZS1hNjBmLTNhYjZmMGQ2OTNmMyIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MTI5NTY3MSwiZXhwIjoxNzYxMjk1NzMxfQ.TWFe_Vzv9PIFJkbV23syp8h7rVSHTv4FGOiQYcwF4Jo

{
  "oldPassword": "Mrco@123_",
  "newPassword": "NewPassword456!"
}
