### Register new user
POST https://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "pippo",
  "email": "pippo@gmail.com",
  "password": "Mrco@123_"
}

### Register new user
POST https://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "baudo",
  "email": "baudo@gmail.com",
  "password": "Mrco@123_"
}

###

### Login (copy the refreshToken from response)
# @name login
POST https://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "baudo@gmail.com",
  "password": "Mrco@123_"
}

###

### Logout (paste refreshToken value from login response below)
DELETE https://localhost:3000/auth/logout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY2Mzc0Yzk5LTBjODEtNGM0ZC1iMmQ2LTRjOTVjZmI1NmQ3MCIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MjE3MDcwNCwiZXhwIjoxNzYyNzc1NTA0fQ.RiCIDZ5xYCb0KuWjOzdEwdQIcnizJ-rCnnuzl0RSmIE

###

### Refresh access token using stored refresh token cookie
POST https://localhost:3000/auth/token

###

### Valid token validation
POST https://localhost:3000/auth/validate-token

###

### Missing token validation (should return 400 Bad Request)
POST https://localhost:3001/validate-token
Content-Type: application/json
x-internal-api-key: 1234

{}

###

### Verify 2FA code
POST https://localhost:3000/auth/2fa
Content-Type: application/json

{
  "userId": "c9d90c36-ce10-4386-b9fc-7caaae892864",
  "otpCode": "295237"
}

###

PUT https://localhost:3000/auth/enable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDkwYzM2LWNlMTAtNDM4Ni1iOWZjLTdjYWFhZTg5Mjg2NCIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MTY4ODYzMywiZXhwIjoxNzYxNjg5NTMzfQ.1KOzTVso2tiMYe2ZKqVwQkWwBt3RKQvys_h-TgXBCyU

{
  "tfaEnabled": true
}

###

PUT https://localhost:3000/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZjMjIzZTQwLWM2NzQtNGQ0ZS05ZjQ0LTlmZDkzN2JhODU5ZCIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MTI5ODYwOCwiZXhwIjoxNzYxMjk4NjY4fQ.PAiASYTBLlNNeLBWJIuvb-hXVefwUZU4f8KUDnj7XQ4

{
  "oldPassword": "Mrco@123_",
  "newPassword": "newPassword456!"
}

###

DELETE https://localhost:3000/auth/delete-account
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlODk1ODczLWNhYzItNGU1Mi05M2MyLWE2ZTE3NzA3NGVkNiIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MjE4MTk1MSwiZXhwIjoxNzYyMTgyODUxfQ.gj-rEVj7e9Ro0gRXguwkfeVk9SgOIeWrDBbtGoqUvu4