GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhNzI4OWIwLWQyYjAtNDdhYy1hNzVlLTZhYjkzZGQ1NTM1MCIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MTU2Mzg2MCwiZXhwIjoxNzYxNTY0NzYwfQ.kyszR9UFrV_Sr5wsg-SU_5ordC6JyFH_QnhSZvizI-E

###

PUT http://localhost:3000/users/update-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YmU3ZDY0LTkwMzUtNDJmMy1iNzc2LWEyOGZmMTIzZjJjNyIsImVtYWlsIjoiY2VjY2FyZWxsaW03QGdtYWlsLmNvbSIsImlhdCI6MTc2MTU2MzkxMSwiZXhwIjoxNzYxNTY0ODExfQ.4i_tkbwWCl7yBFTxGJCMo9TJyXw58Crb_rxVOgxVs78
Content-Type: application/json

{
	  "newUsername": "MARCO_NEW5766564",
	  "newLanguage": "it"
}